@echo off
echo Adding VITE_SUPABASE_ANON_KEY...
call npx vercel env add VITE_SUPABASE_ANON_KEY production --value sb_publishable_6JyYZGd53Kdxe-qzUtKyhw_j_VXMCgF --yes --force
echo Adding VITE_RESEND_API_KEY...
call npx vercel env add VITE_RESEND_API_KEY production --value re_HSSwuZrh_89q997NWZ2BGmZgiHq29Kvb2 --yes --force
echo Adding VITE_NOTION_TOKEN...
call npx vercel env add VITE_NOTION_TOKEN production --value ntn_u684166844597jG2iHrb1RhYFIhxIT0mwsna3GHwVVS4X3 --yes --force
echo Adding VITE_NOTION_DATABASE_ID...
call npx vercel env add VITE_NOTION_DATABASE_ID production --value 34e197cb935d800893b3e3ac38f27dda --yes --force
echo Done.
